version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            # python3 -m venv venv
            # . venv/bin/activate
            sudo pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            # . venv/bin/activate
            (python -m pytest -v)
#            cd ./tests
#            (python -m pytest -v)

      - persist_to_workspace:
          root: ./
          paths:
            - ./*

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  lunch-n-learn:
    jobs:
      - unit_test
